name: install-jest
on: [push]
jobs:
  check-bats-version:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: '14'
      - run: npm install -g jest
      - run: jest --version
      - name: Printing a secret
        shell: bash
        env: 
          TEST_SECRET: ${{ secrets.TEST_REPO_SECRET }}
        run: |
          echo $TEST_SECRET
      - name: Custom JavaScript action
        uses: ./actions/hello-world-action
        id: greet
        with:
          who-to-greet: 'Charan Teja Koneru'
      - name: Get the output from custom actions
        run: echo "The time was ${{ steps.hello.outputs.time }}"
